	tilepal 0, GRAY, RED, RED, RED, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, RED, RED, GRAY, GRAY, GRAY
	tilepal 0, GRAY, RED, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW
	tilepal 0, WATER, WATER, RED, RED, RED, YELLOW, GRAY, GRAY
	tilepal 0, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, RED, BROWN
	tilepal 0, GRAY, RED, GRAY, GRAY, RED, GRAY, WATER, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, RED, RED, GRAY, RED, BROWN, BROWN, GRAY, BROWN
	tilepal 0, GRAY, GRAY, WATER, WATER, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, WATER, WATER, WATER, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, WATER, WATER, WATER, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, GRAY, GREEN, GREEN, GRAY, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, GRAY, TEXT, TEXT, GRAY, GRAY, GRAY, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, GRAY, RED, RED, GRAY
